### ISSUE TITLE
Microworks links no longer work

### ISSUE THREAD

**Issue by missaugustina** [EGG-electric-unicycle/documentation#3]
Microworks seems to have disappeared. The links resolve to an Alibaba 404 page and the company seems to have disappeared. Maybe you could update the documentation for alternative suggestions?

**Comment by casainho** [comment]
Hi. Thanks for the interest. If I can help you more, please tell.

Contacted them today and edited the wiki page with:

PLEASE NOTE: MicroWorks website on Alibaba is currently closed. I contacted Mr. Lee from MicroWorks and got an answer saying they will re-arrange their website in Alibaba in June 2017. Anyone can contact him to buy the components, on skype or whatsapp:
- 0086-136 6042 4065  ( whatsapp )
- Skype:  lizhigang540

**Comment by R3yn4ld** [comment]
Hi,

What's up about this, do you have any news?
Is the factory still making parts or a sold out may happen?

++
Reynald RolluS

**Comment by R3yn4ld** [comment]
Hi,

What's up about this, do you have any news?
Is the factory still making parts or a sold out may happen?

++
Reynald RolluS

**Comment by KaiGrassnick** [comment]
MW has its focus on scooter and skateboards now.

You can still contact them, read here pls: https://forum.electricunicycle.org/topic/9642-microworks-is-coming-back-again/

closing this issue
